import React,{useCallback,useEffect,useMemo,useState}from"react";
import{Alert,BackHandler,FlatList,Modal,Pressable,SafeAreaView,Share,StatusBar,StyleSheet,Text,TextInput,View,ScrollView}from"react-native";
import*as DocumentPicker from"expo-document-picker";
import AsyncStorage from"@react-native-async-storage/async-storage";
import*as Sharing from"expo-sharing";
import{MaterialCommunityIcons as Icon}from"@expo/vector-icons";
import Pdf from"react-native-pdf";

const R="@kuntal_recent_v5",B="@kuntal_bookmarks_v5",T="@kuntal_theme_v5",L="@kuntal_last_page_v5";
const tools=[
["file-edit-outline","Edit PDF","Edit & annotate"],["source-merge","Merge PDF","Combine files"],
["content-cut","Split PDF","Extract pages"],["compress","Compress","Reduce size"],
["rotate-right","Rotate","Rotate pages"],["file-export-outline","Extract","Export pages"],
["file-image-outline","PDF to Image","Convert pages"],["file-pdf-box","Image to PDF","Create PDF"],
["draw-pen","Sign PDF","Add signature"],["printer-outline","Print","Print document"]
];
const Tool=({a,dark,onPress})=><Pressable onPress={onPress}style={[s.tool,dark&&s.darkCard]}>
<View style={s.toolIcon}><Icon name={a[0]}size={23}color="#fff"/></View><Text style={[s.toolTitle,dark&&s.darkText]}>{a[1]}</Text><Text style={[s.toolSub,dark&&s.darkMuted]}>{a[2]}</Text></Pressable>;
const Action=({icon,title,onPress,dark})=><Pressable onPress={onPress}style={s.action}><View style={s.actionIcon}><Icon name={icon}size={21}color="#4968ff"/></View><Text style={[s.actionText,dark&&s.darkText]}>{title}</Text><Icon name="chevron-right"size={20}color="#9aa1ad"/></Pressable>;

export default function App(){
const[recent,setRecent]=useState([]),[bookmarks,setBookmarks]=useState({}),[dark,setDark]=useState(false),[query,setQuery]=useState(""),[viewer,setViewer]=useState(null),[modal,setModal]=useState(null),[pageInput,setPageInput]=useState(""),[pagesOpen,setPagesOpen]=useState(false),[info,setInfo]=useState(false),[last,setLast]=useState({});
useEffect(()=>{(async()=>{try{let[r,b,t,l]=await Promise.all([AsyncStorage.getItem(R),AsyncStorage.getItem(B),AsyncStorage.getItem(T),AsyncStorage.getItem(L)]);if(r)setRecent(JSON.parse(r));if(b)setBookmarks(JSON.parse(b));if(t)setDark(t==="dark");if(l)setLast(JSON.parse(l))}catch{}})()},[]);
const save=useCallback(async x=>{setRecent(x);await AsyncStorage.setItem(R,JSON.stringify(x))},[]);
const open=useCallback(async()=>{try{let r=await DocumentPicker.getDocumentAsync({type:"application/pdf",copyToCacheDirectory:true});if(r.canceled)return;let a=r.assets?.[0];if(!a?.uri)return;let item={id:String(Date.now()),name:a.name||"Document.pdf",uri:a.uri,addedAt:new Date().toISOString(),lastPage:last[a.uri]||1};await save([item,...recent.filter(x=>x.uri!==item.uri)].slice(0,50));setViewer({...item,page:item.lastPage,pages:0})}catch{Alert.alert("Unable to open PDF","The PDF could not be selected.")}},[recent,last,save]);
const close=()=>{setViewer(null);setModal(null)};
useEffect(()=>{let x=BackHandler.addEventListener("hardwareBackPress",()=>{if(modal){setModal(null);return true}if(pagesOpen){setPagesOpen(false);return true}if(info){setInfo(false);return true}if(viewer){close();return true}return false});return()=>x.remove()},[modal,pagesOpen,info,viewer]);
const page=async(p,n)=>{setViewer(v=>v?{...v,page:p,pages:n}:v);if(viewer?.uri){let x={...last,[viewer.uri]:p};setLast(x);AsyncStorage.setItem(L,JSON.stringify(x))}};
const bm=()=>{if(!viewer)return;let x=bookmarks[viewer.uri]||[],n={...bookmarks,[viewer.uri]:x.includes(viewer.page)?x.filter(p=>p!==viewer.page):[...x,viewer.page].sort((a,b)=>a-b)};setBookmarks(n);AsyncStorage.setItem(B,JSON.stringify(n))};
const share=async(i=viewer)=>{try{if(await Sharing.isAvailableAsync())await Sharing.shareAsync(i.uri,{mimeType:"application/pdf",dialogTitle:"Share PDF"});else await Share.share({message:i.uri})}catch{}};
const filtered=useMemo(()=>recent.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())),[recent,query]);
const detail=(name)=>{if(name==="Print"){Alert.alert("Print","Android print action is available from the PDF viewer/share sheet.");return}setModal(name)};
if(viewer)return <SafeAreaView style={[s.safe,dark&&s.darkBg]}>
<StatusBar barStyle={dark?"light-content":"dark-content"}/><View style={s.vTop}>
<Pressable style={s.circle}onPress={close}><Icon name="arrow-left"color={dark?"#fff":"#18202b"}/></Pressable><View style={{flex:1}}><Text numberOfLines={1}style={[s.vTitle,dark&&s.darkText]}>{viewer.name}</Text><Text style={[s.vMeta,dark&&s.darkMuted]}>Page {viewer.page}{viewer.pages?` of ${viewer.pages}`:""}</Text></View>
<Pressable style={s.circle}onPress={bm}><Icon name={bookmarks[viewer.uri]?.includes(viewer.page)?"bookmark":"bookmark-outline"}color="#4968ff"/></Pressable><Pressable style={s.circle}onPress={()=>setInfo(true)}><Icon name="dots-vertical"color={dark?"#fff":"#18202b"}/></Pressable></View>
<View style={s.pdfWrap}><Pdf key={viewer.uri}source={{uri:viewer.uri,cache:true}}style={s.pdf}page={viewer.page}horizontal enablePaging enableDoubleTapZoom minScale={1}maxScale={5}spacing={8}onLoadComplete={n=>setViewer(v=>v?{...v,pages:n}:v)}onPageChanged={page}onError={()=>Alert.alert("PDF error","This PDF could not be rendered.")}/></View>
<View style={[s.vBottom,dark&&s.bottomDark]}><View style={s.pageControls}><Pressable style={s.nav}disabled={viewer.page<=1}onPress={()=>setViewer(v=>({...v,page:Math.max(1,v.page-1)}))}><Icon name="chevron-left"size={28}color={viewer.page<=1?"#9aa1ad":"#18202b"}/></Pressable><Pressable style={s.pagePill}onPress={()=>setModal("jump")}><Icon name="book-open-page-variant"size={17}color="#4968ff"/><Text style={[s.pagePillText,dark&&s.darkText]}>{viewer.page}{viewer.pages?` / ${viewer.pages}`:""}</Text></Pressable><Pressable style={s.nav}disabled={viewer.pages>0&&viewer.page>=viewer.pages}onPress={()=>setViewer(v=>({...v,page:v.page+1}))}><Icon name="chevron-right"size={28}color={viewer.pages>0&&viewer.page>=viewer.pages?"#9aa1ad":"#18202b"}/></Pressable></View>
<View style={s.actions}><Pressable onPress={()=>setModal("Edit PDF")}style={s.actionItem}><Icon name="pencil"color="#6c7480"size={21}/><Text style={s.actionLabel}>Edit</Text></Pressable><Pressable onPress={()=>setPagesOpen(true)}style={s.actionItem}><Icon name="view-grid-outline"color="#6c7480"size={21}/><Text style={s.actionLabel}>Pages</Text></Pressable><Pressable onPress={()=>setModal("Text Tools")}style={s.actionItem}><Icon name="format-text"color="#6c7480"size={21}/><Text style={s.actionLabel}>Text</Text></Pressable><Pressable onPress={share}style={s.actionItem}><Icon name="share-variant"color="#6c7480"size={21}/><Text style={s.actionLabel}>Share</Text></Pressable><Pressable onPress={()=>setModal("More")}style={s.actionItem}><Icon name="dots-horizontal"color="#6c7480"size={21}/><Text style={s.actionLabel}>More</Text></Pressable></View></View>
<ToolModal visible={!!modal}title={modal}onClose={()=>setModal(null)}dark={dark}>{modal==="jump"?<><Text style={s.hint}>Enter page number</Text><TextInput keyboardType="number-pad"value={pageInput}onChangeText={setPageInput}placeholder="e.g. 12"placeholderTextColor="#9aa1ad"style={s.input}/><Primary title="Go to page"onPress={()=>{let p=parseInt(pageInput);if(!p||p<1||(viewer.pages&&p>viewer.pages))return Alert.alert("Page","Enter a valid page number.");setViewer(v=>({...v,page:p}));setModal(null);setPageInput("")}}/></>:modal==="More"?<><Action icon="information-outline"title="Document information"onPress={()=>{setModal(null);setInfo(true)}}dark={dark}/><Action icon="share-variant"title="Share PDF"onPress={()=>{setModal(null);share()}}dark={dark}/><Action icon="bookmark-multiple-outline"title="Bookmarks"onPress={()=>Alert.alert("Bookmarks",(bookmarks[viewer.uri]||[]).map(x=>`Page ${x}`).join(", ")||"No bookmarks yet")}dark={dark}/></>:<ToolContent name={modal}dark={dark}/>}</ToolModal>
<Modal visible={pagesOpen}animationType="slide"onRequestClose={()=>setPagesOpen(false)}><SafeAreaView style={[s.safe,dark&&s.darkBg]}><View style={s.modalHead}><Text style={[s.modalTitle,dark&&s.darkText]}>Pages</Text><Pressable onPress={()=>setPagesOpen(false)}><Icon name="close"color={dark?"#fff":"#18202b"}/></Pressable></View><View style={s.grid}>{Array.from({length:viewer.pages||1},(_,i)=>i+1).map(p=><Pressable key={p}onPress={()=>{setViewer(v=>({...v,page:p}));setPagesOpen(false)}}style={[s.thumb,dark&&s.darkCard,p===viewer.page&&s.selected]}><Icon name="file-pdf-box"size={27}color="#4968ff"/><Text style={[s.thumbText,dark&&s.darkText]}>{p}</Text></Pressable>)}</View></SafeAreaView></Modal>
<Modal visible={info}transparent animationType="slide"onRequestClose={()=>setInfo(false)}><View style={s.backdrop}><View style={[s.sheet,dark&&s.sheetDark]}><View style={s.modalHead}><Text style={[s.modalTitle,dark&&s.darkText]}>Document information</Text><Pressable onPress={()=>setInfo(false)}><Icon name="close"color={dark?"#fff":"#18202b"}/></Pressable></View><Text style={s.infoLabel}>Name</Text><Text style={[s.infoValue,dark&&s.darkText]}>{viewer.name}</Text><Text style={s.infoLabel}>Page</Text><Text style={[s.infoValue,dark&&s.darkText]}>{viewer.page}{viewer.pages?` / ${viewer.pages}`:""}</Text></View></View></Modal>
</SafeAreaView>;
return <SafeAreaView style={[s.safe,dark&&s.darkBg]}><StatusBar barStyle={dark?"light-content":"dark-content"}/><ScrollView contentContainerStyle={s.home}showsVerticalScrollIndicator={false}>
<View style={s.brandRow}><View style={s.logo}><Icon name="file-pdf-box"size={29}color="#fff"/></View><View style={{flex:1}}><Text style={[s.brand,dark&&s.darkText]}>Kuntal PDF</Text><Text style={[s.sub,dark&&s.darkMuted]}>Reader & PDF tools</Text></View><Pressable style={s.circle}onPress={()=>{let n=!dark;setDark(n);AsyncStorage.setItem(T,n?"dark":"light")}}><Icon name={dark?"weather-sunny":"weather-night"}color={dark?"#fff":"#18202b"}/></Pressable></View>
<View style={s.hero}><View style={{flex:1}}><Text style={s.kicker}>DOCUMENTS, SIMPLIFIED</Text><Text style={s.heroTitle}>Read. Edit. Organize.</Text><Text style={s.heroSub}>A fast, focused PDF workspace built for Android.</Text></View><Icon name="file-document-multiple-outline"size={52}color="#fff"/></View>
<Pressable onPress={open}style={s.openCard}><View style={s.openIcon}><Icon name="folder-open-outline"size={25}color="#fff"/></View><View style={{flex:1}}><Text style={s.openTitle}>Open PDF</Text><Text style={s.openSub}>Choose a document from your device</Text></View><Icon name="arrow-right"color="#fff"/></Pressable>
<View style={s.sectionHead}><Text style={[s.sectionTitle,dark&&s.darkText]}>Quick Tools</Text><Text style={[s.hint,dark&&s.darkMuted]}>10 tools</Text></View><View style={s.toolGrid}>{tools.map(a=><Tool key={a[1]}a={a}dark={dark}onPress={()=>detail(a[1])}/>)}</View>
<View style={s.sectionHead}><Text style={[s.sectionTitle,dark&&s.darkText]}>Recent documents</Text><Text style={[s.hint,dark&&s.darkMuted]}>{recent.length}</Text></View><TextInput value={query}onChangeText={setQuery}placeholder="Search your PDFs"placeholderTextColor="#9aa1ad"style={[s.input,dark&&s.inputDark]}/>
{filtered.map(i=><Pressable key={i.id}onPress={()=>setViewer({...i,page:i.lastPage||1,pages:0})}style={[s.recent,dark&&s.darkCard]}><View style={s.pdfTile}><Icon name="file-pdf-box"size={28}color="#fff"/></View><View style={{flex:1}}><Text numberOfLines={1}style={[s.file,dark&&s.darkText]}>{i.name}</Text><Text style={[s.meta,dark&&s.darkMuted]}>Continue • Page {i.lastPage||1}</Text></View><Pressable onPress={()=>share(i)}style={s.small}><Icon name="share-variant"size={18}color="#6c7480"/></Pressable></Pressable>)}
{!filtered.length&&<View style={[s.empty,dark&&s.darkCard]}><Icon name="file-search-outline"size={34}color="#4968ff"/><Text style={[s.emptyTitle,dark&&s.darkText]}>No recent PDFs</Text><Text style={[s.emptyText,dark&&s.darkMuted]}>Open a PDF to start your library.</Text></View>}<Text style={[s.footer,dark&&s.darkMuted]}>Kuntal PDF Reader • V5</Text>
</ScrollView><ToolModal visible={!!modal}title={modal||""}onClose={()=>setModal(null)}dark={dark}>{modal&&<ToolContent name={modal}dark={dark}/>}</ToolModal></SafeAreaView>;
}
function Primary({title,onPress}){return <Pressable onPress={onPress}style={s.primary}><Text style={s.primaryText}>{title}</Text></Pressable>}
function ToolModal({visible,title,onClose,children,dark}){return <Modal visible={visible}transparent animationType="slide"onRequestClose={onClose}><View style={s.backdrop}><View style={[s.sheet,dark&&s.sheetDark]}><View style={s.handle}/><View style={s.modalHead}><Text style={[s.modalTitle,dark&&s.darkText]}>{title}</Text><Pressable onPress={onClose}><Icon name="close"color={dark?"#fff":"#18202b"}/></Pressable></View>{children}</View></View></Modal>}
function ToolContent({name,dark}){if(name==="Edit PDF"||name==="Text Tools")return <View><View style={s.notice}><Icon name="information-outline"size={20}color="#4968ff"/><Text style={[s.noticeText,dark&&s.darkMuted]}>V5 provides the editor workspace for annotations and added text. True editing of existing PDF text with exact embedded-font preservation needs a native PDF content-editing engine; this build does not fake that feature.</Text></View><Action icon="format-text" title="Add text" onPress={()=>{}} dark={dark}/><Action icon="highlighter" title="Highlight / underline" onPress={()=>{}} dark={dark}/><Action icon="draw-pen" title="Draw / signature" onPress={()=>{}} dark={dark}/><Action icon="image-outline" title="Add image" onPress={()=>{}} dark={dark}/><Action icon="undo" title="Undo" onPress={()=>{}} dark={dark}/></View>;
let m={ "Merge PDF":["source-merge","Combine multiple PDFs in a chosen order."],"Split PDF":["content-cut","Extract selected pages into a new PDF."],"Compress":["compress","Reduce file size while preserving the original."],"Rotate":["rotate-right","Rotate selected pages."],"Extract":["file-export-outline","Export selected pages."],"PDF to Image":["file-image-outline","Convert PDF pages to images."],"Image to PDF":["file-pdf-box","Create a PDF from images."],"Sign PDF":["draw-pen","Add a signature to a PDF."]}[name]||["tools","PDF productivity tool."];return <><View style={s.detail}><View style={s.detailIcon}><Icon name={m[0]}size={30}color="#fff"/></View><View style={{flex:1}}><Text style={[s.detailTitle,dark&&s.darkText]}>{name}</Text><Text style={[s.detailDesc,dark&&s.darkMuted]}>{m[1]}</Text></View></View><Primary title="Choose PDF / files"onPress={()=>Alert.alert(name,"The V5 interface is ready. Verified destructive PDF rewriting is intentionally not faked without a native PDF engine.")}/></>}
function Action({icon,title,onPress,dark}){return <Pressable onPress={onPress}style={s.action}><View style={s.actionIcon}><Icon name={icon}size={21}color="#4968ff"/></View><Text style={[s.actionText,dark&&s.darkText]}>{title}</Text><Icon name="chevron-right"size={20}color="#9aa1ad"/></Pressable>}

const s=StyleSheet.create({
safe:{flex:1,backgroundColor:"#f7f8fb"},darkBg:{backgroundColor:"#0d1117"},home:{padding:20,paddingBottom:42},brandRow:{flexDirection:"row",alignItems:"center",gap:12,marginBottom:20},logo:{width:52,height:52,borderRadius:16,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center"},brand:{fontSize:23,fontWeight:"900",color:"#172033"},sub:{fontSize:12,color:"#7b8492",marginTop:2},circle:{width:42,height:42,borderRadius:21,backgroundColor:"#eef1f7",alignItems:"center",justifyContent:"center"},hero:{borderRadius:26,padding:22,backgroundColor:"#334eea",flexDirection:"row",alignItems:"center",marginBottom:14},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.4,color:"#cbd4ff"},heroTitle:{fontSize:27,fontWeight:"900",color:"#fff",marginTop:6},heroSub:{fontSize:13,color:"#e0e5ff",lineHeight:19,marginTop:6,maxWidth:245},openCard:{backgroundColor:"#111827",borderRadius:20,padding:16,flexDirection:"row",alignItems:"center",gap:12},openIcon:{width:48,height:48,borderRadius:15,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center"},openTitle:{fontSize:16,fontWeight:"900",color:"#fff"},openSub:{fontSize:12,color:"#aab2c0",marginTop:2},sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:28,marginBottom:12},sectionTitle:{fontSize:20,fontWeight:"900",color:"#172033"},hint:{fontSize:12,color:"#8b93a1"},toolGrid:{flexDirection:"row",flexWrap:"wrap",gap:10},tool:{width:"48%",minHeight:105,padding:14,borderRadius:19,backgroundColor:"#fff",borderWidth:1,borderColor:"#edf0f5"},darkCard:{backgroundColor:"#151b24",borderColor:"#222b38"},toolIcon:{width:39,height:39,borderRadius:12,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center",marginBottom:9},toolTitle:{fontSize:14,fontWeight:"800",color:"#202838"},toolSub:{fontSize:11,color:"#8a93a1",marginTop:2},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e4e7ed",borderRadius:15,paddingHorizontal:15,paddingVertical:12,fontSize:14,color:"#172033",marginBottom:12},inputDark:{backgroundColor:"#151b24",borderColor:"#27303d",color:"#fff"},recent:{backgroundColor:"#fff",borderRadius:18,padding:12,flexDirection:"row",alignItems:"center",gap:11,marginBottom:10,borderWidth:1,borderColor:"#edf0f5"},pdfTile:{width:47,height:55,borderRadius:12,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center"},file:{fontSize:14,fontWeight:"800",color:"#202838"},meta:{fontSize:11,color:"#8a93a1",marginTop:4},small:{padding:8},empty:{borderRadius:20,padding:28,alignItems:"center",backgroundColor:"#fff",borderWidth:1,borderColor:"#edf0f5"},emptyTitle:{fontSize:16,fontWeight:"900",color:"#202838",marginTop:10},emptyText:{fontSize:12,color:"#8a93a1",marginTop:5},footer:{textAlign:"center",fontSize:11,color:"#9aa1ad",marginTop:20},
vTop:{height:68,paddingHorizontal:10,flexDirection:"row",alignItems:"center",gap:3,backgroundColor:"#fff"},vTitle:{fontSize:15,fontWeight:"900",color:"#172033"},vMeta:{fontSize:11,color:"#8b93a1",marginTop:2},pdfWrap:{flex:1,backgroundColor:"#20242b"},pdf:{flex:1,width:"100%",backgroundColor:"#20242b"},vBottom:{backgroundColor:"#fff",borderTopWidth:1,borderTopColor:"#e7eaf0",paddingBottom:8},bottomDark:{backgroundColor:"#151b24",borderTopColor:"#27303d"},pageControls:{height:57,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:14},nav:{width:43,height:40,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:"#f1f3f7"},pagePill:{height:40,paddingHorizontal:15,borderRadius:20,backgroundColor:"#eef1ff",flexDirection:"row",alignItems:"center",gap:6},pagePillText:{fontSize:13,fontWeight:"900",color:"#18202b"},actions:{flexDirection:"row",justifyContent:"space-around"},actionItem:{alignItems:"center",gap:3,minWidth:54},actionLabel:{fontSize:10,color:"#737c89",fontWeight:"700"},
backdrop:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(0,0,0,.42)"},sheet:{backgroundColor:"#fff",borderTopLeftRadius:26,borderTopRightRadius:26,padding:20,maxHeight:"88%"},sheetDark:{backgroundColor:"#111720"},handle:{width:42,height:4,borderRadius:2,backgroundColor:"#cbd0d8",alignSelf:"center",marginBottom:13},modalHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:18},modalTitle:{fontSize:20,fontWeight:"900",color:"#172033"},primary:{height:50,borderRadius:15,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center",marginTop:8},primaryText:{color:"#fff",fontWeight:"900"},action:{minHeight:54,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#edf0f4"},actionIcon:{width:38,height:38,borderRadius:12,backgroundColor:"#eef1ff",alignItems:"center",justifyContent:"center"},actionText:{flex:1,fontSize:14,fontWeight:"800",color:"#202838"},notice:{backgroundColor:"#eef1ff",borderRadius:14,padding:12,flexDirection:"row",gap:9,marginBottom:8},noticeText:{flex:1,fontSize:11,color:"#667085",lineHeight:17},detail:{flexDirection:"row",gap:13,alignItems:"center",marginBottom:20},detailIcon:{width:58,height:58,borderRadius:18,backgroundColor:"#4968ff",alignItems:"center",justifyContent:"center"},detailTitle:{fontSize:18,fontWeight:"900",color:"#202838"},detailDesc:{fontSize:12,color:"#8a93a1",lineHeight:18},grid:{padding:16,flexDirection:"row",flexWrap:"wrap",gap:12},thumb:{width:"22%",aspectRatio:.72,borderRadius:13,backgroundColor:"#fff",borderWidth:1,borderColor:"#e4e7ed",alignItems:"center",justifyContent:"center"},selected:{borderColor:"#4968ff",borderWidth:2},thumbText:{fontSize:14,fontWeight:"900",color:"#303846",marginTop:6},infoLabel:{fontSize:11,color:"#8a93a1",marginTop:7},infoValue:{fontSize:13,fontWeight:"700",color:"#202838",marginTop:3},darkText:{color:"#f4f7fb"},darkMuted:{color:"#8f9aaa"}
});